// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models
{
    public partial class Issue
    {
        [Key]
        public int Id { get; set; }
        [Column("Address_Id")]
        public int AddressId { get; set; }
        public string Detail { get; set; }
        [Column("Problem_Address_Id")]
        public int ProblemAddressId { get; set; }
        [Column("Problem_Unit_Id")]
        public int? ProblemUnitId { get; set; }
        [Column("Location_Id")]
        public int? LocationId { get; set; }
        [Column("Assigned_User_id")]
        public int AssignedUserId { get; set; }
        public bool Anonymous { get; set; }
    }
}