// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models
{
    public partial class Property
    {
        [Key]
        public int Id { get; set; }
        public string Address { get; set; }
        [StringLength(10)]
        public string Alert { get; set; }
        [Column("Documents_Detail_Id")]
        public int? DocumentsDetailId { get; set; }
        [Column("Checkpoints_Detail_id")]
        public int? CheckpointsDetailId { get; set; }
        [Column("Tours_Detail_Id")]
        public int? ToursDetailId { get; set; }
        [Column("Geofences_Detail_Id")]
        public int? GeofencesDetailId { get; set; }
        [Column("Issue_Types_Detail_Id")]
        public int? IssueTypesDetailId { get; set; }
        [Column("Locations_Detail_Id")]
        public int? LocationsDetailId { get; set; }
        [Column("Phone_Numbers_Detail_Id")]
        public int? PhoneNumbersDetailId { get; set; }
        [Column("Tasks_Detail_Id")]
        public int? TasksDetailId { get; set; }
        [Column("Managements_Detail_Id")]
        public int? ManagementsDetailId { get; set; }
        [Column("Devices_Detail_Id")]
        public int? DevicesDetailId { get; set; }
        [Column("Notifications_Detail_Id")]
        public int? NotificationsDetailId { get; set; }
        [Column("Invoices_Detail_Id")]
        public int? InvoicesDetailId { get; set; }
    }
}